# Jekyll Defaults
title: AM Notebook
description: Articles, Notes, Instructions, Snippets
baseurl: "/" # the subpath of your site, e.g. /blog

url: "https://andreymatin.github.io/"
github: https://github.com/andreymatin/andreymatin.github.io
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
